#!/bin/sh

base='		i386 i486 i586'
pentium='	pentium pentium-mmx pentiumpro i686 pentium2 pentium3 pentium3m pentium-m pentium4 pentium4m prescott nocona'
core='		core2 nehalem westmere sandybridge ivybridge haswell broadwell knl skylake-avx512'
atom='		bonnell silvermont'
athlon='	k6 k6-2 k6-3 athlon athlon-tbird athlon-4 athlon-xp athlon-mp'
amd64='		k8 opteron athlon64 athlon-fx k8-sse3 opteron-sse3 athlon64-sse3 amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2'
other='		winchip-c6 winchip2 c3 c3-2 c7 samuel-2 nehemiah esther eden-x2 eden-x4 nano nano-1000 nano-2000 nano-3000 nano-x2 nano-x4 geode'

archs="$base $pentium $core $atom $athlon $amd64 $other"

dryes() {
	local sum=0 res=0
	for i in $(seq 1 $1); do
		res=$(schedtool -F -p 99 -n -19 -a 0x1 -e ./dry 2>/dev/null |awk '/^Dhrystones/{print$4}')
		sum=$((sum + res))
	done
	echo -n $((sum / $1))
}

echo 'CPU,32 bit,64 bit'
for a in $archs; do
	echo -n "$a"
	for b in 32 64; do
		echo -n ,
		make -s clean all CFLAGS="-m$b -mfpmath=sse -O3 -march=$a" LDFLAGS=-m$b >/dev/null 2>/dev/null || continue
		dryes 5
	done
	echo
done
